export const initialCards = [
  {
    title: 'Нерпа',
    image: new URL('../images/places/nerpa-shine.jpeg', import.meta.url),
    images: [
      new URL('../images/places/nerpa-shine_thumb.jpeg', import.meta.url),
      new URL('../images/places/nerpa-shine_480w.jpeg', import.meta.url),
      new URL('../images/places/nerpa-shine_1134w.jpeg', import.meta.url),
      new URL('../images/places/nerpa-shine_1637w.jpeg', import.meta.url),
      new URL('../images/places/nerpa-shine_2000w.jpeg', import.meta.url),
    ],
    imageAlt: 'Нерпа в сиянии водорослей',
    initial: true,
  },
  {
    title: 'Кораллы',
    image: new URL('../images/places/green-coral.jpeg', import.meta.url),
    images: [
      new URL('../images/places/green-coral_thumb.jpeg', import.meta.url),
      new URL('../images/places/green-coral_480w.jpeg', import.meta.url),
      new URL('../images/places/green-coral_1050w.jpeg', import.meta.url),
      new URL('../images/places/green-coral_1465w.jpeg', import.meta.url),
      new URL('../images/places/green-coral_1760w.jpeg', import.meta.url),
    ],
    imageAlt: 'Колонии Байкала',
    initial: true,
  },
  {
    title: 'Сады Байкала',
    image: new URL('../images/places/baikal-garden.jpeg', import.meta.url),
    images: [
      new URL('../images/places/baikal-garden_thumb.jpeg', import.meta.url),
      new URL('../images/places/baikal-garden_480w.jpeg', import.meta.url),
      new URL('../images/places/baikal-garden_1152w.jpeg', import.meta.url),
      new URL('../images/places/baikal-garden_1695w.jpeg', import.meta.url),
      new URL('../images/places/baikal-garden_2000w.jpeg', import.meta.url),
    ],
    imageAlt: 'Подводный сад',
    initial: true,
  },
  {
    title: 'Чистый лёд',
    image: new URL('../images/places/baikal-ice.jpeg', import.meta.url),
    images: [
      new URL('../images/places/baikal-ice_thumb.jpeg', import.meta.url),
      new URL('../images/places/baikal-ice_480w.jpeg', import.meta.url),
      new URL('../images/places/baikal-ice_817w.jpeg', import.meta.url),
      new URL('../images/places/baikal-ice_1102w.jpeg', import.meta.url),
      new URL('../images/places/baikal-ice_1260w.jpeg', import.meta.url),
    ],
    imageAlt: 'Байкальский лёд',
    initial: true,
  },
  {
    title: 'Коралловые рифы',
    image: new URL('../images/places/coral-riff.jpeg', import.meta.url),
    images: [

      new URL('../images/places/coral-riff_thumb.jpeg', import.meta.url),
      new URL('../images/places/coral-riff_480w.jpeg', import.meta.url),
      new URL('../images/places/coral-riff_1143w.jpeg', import.meta.url),
      new URL('../images/places/coral-riff_1604w.jpeg', import.meta.url),
      new URL('../images/places/coral-riff_2000w.jpeg', import.meta.url),
    ],
    imageAlt: 'Рыбка в кораллах',
    initial: true,
  },
  {
    title: 'Подводные леса',
    image: new URL('../images/places/nerpa-in-forest.jpeg', import.meta.url),
    images: [
      new URL('../images/places/nerpa-in-forest_thumb.jpeg', import.meta.url),
      new URL('../images/places/nerpa-in-forest_480w.jpeg', import.meta.url),
      new URL('../images/places/nerpa-in-forest_1131w.jpeg', import.meta.url),
      new URL('../images/places/nerpa-in-forest_1532w.jpeg', import.meta.url),
      new URL('../images/places/nerpa-in-forest_2000w.jpeg', import.meta.url),
    ],
    imageAlt: 'Нерпа в подводном лесу',
    initial: true,
  },
];
