export const initialCards = [
  {
    title: 'Нерпа',
    image: 'nerpa-shine.jpeg',
    imageAlt: 'Нерпа в сиянии водорослей',
    initial: true,
    imageSet: [
      '480w',
      '1134w',
      '1637w',
      '2000w',
    ],
    thumbSet: [
      '282w',
      '564w',
      '846w',
      '1128w',
    ],
  },
  {
    title: 'Кораллы',
    image: 'green-coral.jpeg',
    imageAlt: 'Колонии Байкала',
    initial: true,
    imageSet: [
      '480w',
      '1050w',
      '1465w',
      '1760w',
    ],
    thumbSet: [
      '282w',
      '564w',
      '846w',
      '1128w',
    ],
  },
  {
    title: 'Сады Байкала',
    image: 'baikal-garden.jpeg',
    imageAlt: 'Подводный сад',
    initial: true,
    imageSet: [
      '480w',
      '1152w',
      '1695w',
      '2000w',
    ],
    thumbSet: [
      '282w',
      '564w',
      '846w',
      '1128w',
    ],
  },
  {
    title: 'Чистый лёд',
    image: 'baikal-ice.jpeg',
    imageAlt: 'Байкальский лёд',
    initial: true,
    imageSet: [
      '480w',
      '817w',
      '1102w',
      '1260w',
    ],
    thumbSet: [
      '282w',
      '564w',
      '846w',
      '1128w',
    ],
  },
  {
    title: 'Коралловые рифы',
    image: 'coral-riff.jpeg',
    imageAlt: 'Рыбка в кораллах',
    initial: true,
    imageSet: [
      '480w',
      '1143w',
      '1604w',
      '2000w',
    ],
    thumbSet: [
      '282w',
      '564w',
      '846w',
      '1128w',
    ],
  },
  {
    title: 'Подводные леса',
    image: 'nerpa-in-forest.jpeg',
    imageAlt: 'Нерпа в подводном лесу',
    initial: true,
    imageSet: [
      '480w',
      '1131w',
      '1532w',
      '2000w',
    ],
    thumbSet: [
      '282w',
      '564w',
      '846w',
      '1128w',
    ],
  },
];
